# some notes:
# DocumentCloud's AssetStore operates as a local file system share.  We'll implement
# this as a docker volume shared across CloudCrowd Server, Node and App containers.

version: '3.1'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    restart:
      always
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "dev.dcloud.org:127.0.0.1"
      - "assets.dcloud.org:127.0.0.1"
    volumes:
      - public:/documentcloud/public
  db:
    image: postgres:9.6
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: documentcloud
      POSTGRES_USER: documentcloud
    volumes:
      - ./db/cloud_crowd_development_structure.sql:/docker-entrypoint-initdb.d/cloud_crowd_development_structure.sql
      - ./db/development_structure.sql:/docker-entrypoint-initdb.d/development_structure.sql
      - ./db/analytics_structure.sql:/docker-entrypoint-initdb.d/analytics_structure.sql
  cloud_crowd_server:
    build:
      context: .
      dockerfile: Dockerfile.cloud_crowd_server
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file: ./docker/env.list
    volumes:
      - ./config/cloud_crowd/docker:/cloud_crowd
      - asset_store:/documentcloud/public/asset_store
  cloud_crowd_node:
    build:
      context: .
      dockerfile: Dockerfile.cloud_crowd_node
    depends_on:
      - db
      - cloud_crowd_server
    ports:
      - "9063:9063"
    env_file: ./docker/env.list
    volumes:
      - ./config/cloud_crowd/docker:/cloud_crowd
      - public:/documentcloud/public
      - asset_store:/documentcloud/public/asset_store
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        # docker-compose is extremely dumb and does not have a mechanism for 
        # supplying a file for build arguments.  Instead, one has to use variables 
        # as seen below and include a .env file in the project root.
        github_user:  ${GITHUB_USER:?err}
        github_token: ${GITHUB_TOKEN:?err}
    depends_on:
      - db
      - cloud_crowd_server
      - solr
      - javascript
    env_file: ./docker/env.list
    environment:
      PASSENGER_LOG_FILE: /dev/stdout
      PASSENGER_LOG_LEVEL: 3
      RAILS_LOG_TO_STDOUT: "yes"
    expose:
      - "8765"
    extra_hosts:
      - "dev.dcloud.org:127.0.0.1"
      - "assets.dcloud.org:127.0.0.1"
    volumes:
      - asset_store:/documentcloud/public/asset_store
      - javascript:/documentcloud/public/javascripts/vendor
  javascript:
    build:
      context: .
      dockerfile: Dockerfile.javascript
    volumes:
      - javascript:/javascript
  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
      - "7377:7377"
    env_file: ./docker/env.list

volumes:
  public:
  asset_store:
  javascript: