# some notes:
# DocumentCloud's AssetStore operates as a local file system share.  We'll implement
# this as a docker volume shared across CloudCrowd Server, Node and App containers.

version: '3.1'
services:
  db:
    image: postgres:9.6
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: documentcloud
      POSTGRES_USER: documentcloud
    volumes:
      - ./db/cloud_crowd_development_structure.sql:/docker-entrypoint-initdb.d/cloud_crowd_development_structure.sql
      - ./db/development_structure.sql:/docker-entrypoint-initdb.d/development_structure.sql
      - ./db/analytics_structure.sql:/docker-entrypoint-initdb.d/analytics_structure.sql
  cloud_crowd_server:
    build:
      context: .
      dockerfile: Dockerfile.cloud_crowd_server
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file: ./docker/env.list
    volumes:
      - ./config/cloud_crowd/docker:/cloud_crowd
      - asset_store:/documentcloud/public/asset_store
  cloud_crowd_node:
    build:
      context: .
      dockerfile: Dockerfile.cloud_crowd_node
    depends_on:
      - db
      - cloud_crowd_server
    ports:
      - "9063:9063"
    env_file: ./docker/env.list
    volumes:
      - ./config/cloud_crowd/docker:/cloud_crowd
      - asset_store:/documentcloud/public/asset_store
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        # docker-compose is extremely dumb and does not have a mechanism for 
        # supplying a file for build arguments.  Instead, one has to use variables 
        # as seen below and include a .env file in the project root.
        github_user:  ${GITHUB_USER:?err}
        github_token: ${GITHUB_TOKEN:?err}
    ports:
      - "8765:8765"
    depends_on:
      - db
      - cloud_crowd_server
      - solr
    env_file: ./docker/env.list
    environment:
      PASSENGER_LOG_FILE: /dev/stdout
      PASSENGER_LOG_LEVEL: 3
      RAILS_LOG_TO_STDOUT: "yes"
    volumes:
      - asset_store:/documentcloud/public/asset_store
  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
      - "7377:7377"
    env_file: ./docker/env.list

volumes:
  asset_store:
