defaults: &defaults
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  allow_concurrency: true
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *defaults
  database: dcloud_analytics_development

staging:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
  database: dcloud_analytics_staging

production:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
  database: dcloud_analytics_production

test:
  <<: *defaults
  database: dcloud_analytics_test
