javascript_compressor: closure
template_function: dc._.template
embed_assets: datauri

javascripts:
  note_embed:
    - public/javascripts/vendor/underscore/underscore.js
    - public/javascripts/vendor/sprintf.js
    - public/javascripts/lib/i18n.js
    - public/javascripts/translations/eng.js
    - public/javascripts/translations/spa.js
    - public/javascripts/vendor/jquery/dist/jquery.js
    - public/javascripts/vendor/documentcloud-notes/templates/note_embed.jst
    - public/javascripts/vendor/documentcloud-notes/js/note_embed.js

stylesheets:
  note_embed:
    - public/javascripts/vendor/documentcloud-notes/css/note_embed.css
