:central_server:      http://<%= ENV['CLOUD_CROWD_SERVER_HOST'] %>:<%= ENV['CLOUD_CROWD_SERVER_PORT'] %>
:max_workers:         2
:storage:             filesystem
:actions_path:        ./app/actions
:work_unit_retries:   1