# This is a standard ActiveRecord database.yml file. You can configure it
# to use any database that ActiveRecord supports.



:adapter:  postgresql
:encoding: unicode
:schema_search_path: public
:pool: 10
:dead_connection_timeout: 1
:reaping_frequency: 30
:username: <%= ENV['CLOUD_CROWD_DB_USER'] %>
:password: <%= ENV['CLOUD_CROWD_DB_PASSWORD'] %>
:allow_concurrency: true
:database: <%= ENV['CLOUD_CROWD_DB_NAME'] %>
:host:     <%= ENV['CLOUD_CROWD_DB_HOST'] %>
